events 정보 전달
SMHRD-SafeWatch/safewatch_backend pull request #1
Opened 2024-11-04 06:22 UTC by Totoclub12

정보 전달 기능만 구현 완료

2024-11-06 00:49 UTC, Philipshrimp reviewed
코드 확인 완료했습니다.
전반적으로 변수명이나 클래스 구성 등 알맞게 잘 작성해주셨네요:)
코드 구현하실 때, 불필요한 공백은 가독성을 위해 정리해주시는 것을 권장드립니다.

2024-11-06 00:49 UTC, Philipshrimp commented on build.gradle
@2totwo @HanJaeOk 이 코드에서 다루는 프레임워크 버전 등이 충돌나기 쉽습니다.
서로 사용하시는 버전들 잘 확인하시고 버전 통일 꼭 하셔야 합니다.

2024-11-06 00:49 UTC, Philipshrimp commented on src/main/java/com/sw/sw/security/WebSecurityConfig.java
사용되지 않는 클래스일까요, 아니면 차후에 사용될 클래스일까요?
불필요한 코드 파일은 가급적이면 삭제해서 정리 부탁드립니다.

2024-11-06 00:49 UTC, Philipshrimp commented on src/main/java/com/sw/sw/service/FlaskService.java
여기도 불필요한 영역인지 확인 부탁드립니다.

2024-11-06 01:42 UTC, Philipshrimp requested changes
코멘트 확인 후 수정 부탁드립니다.

2024-11-06 01:42 UTC, Philipshrimp commented on src/main/java/com/sw/sw/entity/Warning.java
> +    private Long detectionId;
변수의 타입을 변경해주세요.

2024-11-07 04:45 UTC, Totoclub12 commented on src/main/java/com/sw/sw/service/FlaskService.java
플라스크를 통해 모델에서 값을 가져오는 부분입니다

2024-11-07 04:46 UTC, Totoclub12 commented on src/main/java/com/sw/sw/security/WebSecurityConfig.java
시큐리티 추가 기능 부분인데 만약 사용하지 않을때 지우겠습니다

2024-11-12 03:25 UTC, 2totwo reviewed
확인했습니다.

2024-11-13 01:08 UTC, Philipshrimp commented
> 확인했습니다.

approve로 코멘트 올려주시면 되겠습니다.

2024-11-13 07:44 UTC, merged